#ifndef GHAND_VERSION_H_
#define GHAND_VERSION_H_

#define GHAND_VERSION_MAJOR 2
#define GHAND_VERSION_MINOR 0
#define GHAND_VERSION_PATCH 0
#define GHAND_VERSION_STRING "2.0.0"

#endif  // GHAND_VERSION_H_
