#ifndef XIAOYAO_VERSION_H_
#define XIAOYAO_VERSION_H_

#define XIAOYAO_VERSION_MAJOR 1
#define XIAOYAO_VERSION_MINOR 0
#define XIAOYAO_VERSION_PATCH 0
#define XIAOYAO_VERSION_STRING "1.0.0"

#endif  // XIAOYAO_VERSION_H_
